### ISSUE TITLE
Is carousel-slider plugin ready for High-Performance Order Storage

### ISSUE THREAD

**Issue by Martje65** [sayful1/carousel-slider#24]
Is carousel-slider ready or considering update the plugin to make it compatible with the new option of WooCommerce “High-Performance Order Storage”

See:

<a href="https://developer.woocommerce.com/2022/09/29/high-performance-order-storage-backward-compatibility-and-synchronization/">High-Performance Order Storage: Backward Compatibility and Synchronization</a>

<a href="https://developer.woocommerce.com/2022/09/14/high-performance-order-storage-progress-report/">High-Performance Order Storage: progress report</a>

<a href="https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#declaring-extension-incompatibility">Github: What is High-Performance Order Storage (HPOS)?</a>

**Comment by sayful1** [comment]
This plugin is not related to Order Storage.
For WooCommerce product carousel, it use `wc_get_products` function that use CRUD layer introduced in WooCommerce 3.0
