### ISSUE TITLE
Additional Security Issues Related to Issue Addressed in Version 2.2.3

### ISSUE THREAD

**Issue by PluginVulnerabilities** [sayful1/carousel-slider#31]
While reviewing the security change made in version 2.2.3, as at least one of our customers is using the plugin, we noticed that there are still a couple of AJAX accessible functions that are lacking a capabilities check and or a nonce check. The function add_slide_template() in the file /modules/HeroCarousel/Ajax.php lacks both, leading to a vulnerability. The function deactivate_feedback() in the file /includes/Admin/Feedback.php is lacking a capabilities check.

**Comment by sayful1** [comment]
All AJAX operations are rechecked and add nonce verification and permission checking.
